angular.module('winatlifeApp').run(['$templateCache', function($templateCache) {
  'use strict';

  $templateCache.put('app/account/login/login.html',
    "<div ng-include=\"'components/navbar/navbar.html'\"></div><div class=container><div class=row><div class=col-sm-12><h1>Login</h1></div><div class=col-sm-12><form class=form name=form ng-submit=login(form) novalidate><div class=form-group><label>Username</label><input type=login name=login class=form-control ng-model=user.login required></div><div class=form-group><label>Password</label><input type=password name=password class=form-control ng-model=user.password required></div><div class=\"form-group has-error\"><p class=help-block ng-show=\"form.login.$error.required && form.password.$error.required && submitted\">Please enter your login and password.</p><p class=help-block ng-show=\"form.login.$error.login && submitted\">Please enter a valid login; it must be between 3 and 16 characters with only letters, numbers, underscores and hyphens</p><p class=help-block>{{ errors.other }}</p></div><div><button class=\"btn btn-inverse btn-lg btn-login\" type=submit>Login</button> <a class=\"btn btn-default btn-lg btn-register\" href=/signup>Register</a></div><hr><div><a class=\"btn btn-facebook\" href=\"\" ng-click=\"loginOauth('facebook')\"><i class=\"fa fa-facebook\"></i> Connect with Facebook</a></div></form></div></div><hr></div>"
  );


  $templateCache.put('app/account/settings/settings.html',
    "<div ng-include=\"'components/navbar/navbar.html'\"></div><div class=container><div class=row><div class=col-sm-12><h1>Change Password</h1></div><div class=col-sm-12><form class=form name=form ng-submit=changePassword(form) novalidate><div class=form-group><label>Current Password</label><input type=password name=password class=form-control ng-model=user.oldPassword mongoose-error><p class=help-block ng-show=form.password.$error.mongoose>{{ errors.other }}</p></div><div class=form-group><label>New Password</label><input type=password name=newPassword class=form-control ng-model=user.newPassword ng-minlength=3 required><p class=help-block ng-show=\"(form.newPassword.$error.minlength || form.newPassword.$error.required) && (form.newPassword.$dirty || submitted)\">Password must be at least 3 characters.</p></div><p class=help-block>{{ message }}</p><button class=\"btn btn-lg btn-primary\" type=submit>Save changes</button></form></div></div></div>"
  );


  $templateCache.put('app/account/signup/signup.html',
    "<div ng-include=\"'components/navbar/navbar.html'\"></div><div class=container><div class=row><div class=col-sm-12><h1>Sign up</h1></div><div class=col-sm-12><form class=form name=form ng-submit=register(form) novalidate><div class=form-group ng-class=\"{ 'has-success': form.name.$valid && submitted,\n" +
    "                                            'has-error': form.name.$invalid && submitted }\"><label>Name</label><input name=name class=form-control ng-model=user.name required><p class=help-block ng-show=\"form.name.$error.required && submitted\">A name is required</p></div><div class=form-group ng-class=\"{ 'has-success': form.login.$valid && submitted,\n" +
    "                                        'has-error': form.login.$invalid && submitted }\"><label>Login</label><input name=login class=form-control ng-model=user.login required><p class=help-block ng-show=\"form.login.$error.required && submitted\">A login is required and must be between 3 to 16 characters containing only letters, numbers, underscores and/or hyphens.</p></div><div class=form-group ng-class=\"{ 'has-success': form.email.$valid && submitted,\n" +
    "                                            'has-error': form.email.$invalid && submitted }\"><label>Email</label><input type=email name=email class=form-control ng-model=user.email required mongoose-error><p class=help-block ng-show=\"form.email.$error.email && submitted\">Doesn't look like a valid email.</p><p class=help-block ng-show=\"form.email.$error.required && submitted\">What's your email address?</p><p class=help-block ng-show=form.email.$error.mongoose>{{ errors.email }}</p></div><div class=form-group ng-class=\"{ 'has-success': form.password.$valid && submitted,\n" +
    "                                            'has-error': form.password.$invalid && submitted }\"><label>Password</label><input type=password name=password class=form-control ng-model=user.password ng-minlength=3 required mongoose-error><p class=help-block ng-show=\"(form.password.$error.minlength || form.password.$error.required) && submitted\">Password must be at least 3 characters.</p><p class=help-block ng-show=form.password.$error.mongoose>{{ errors.password }}</p></div><div><button class=\"btn btn-inverse btn-lg btn-login\" type=submit>Sign up</button> <a class=\"btn btn-default btn-lg btn-register\" href=/login>Login</a></div><hr><div><a class=\"btn btn-facebook\" href=\"\" ng-click=\"loginOauth('facebook')\"><i class=\"fa fa-facebook\"></i> Connect with Facebook</a></div></form></div></div><hr></div>"
  );


  $templateCache.put('app/admin/admin.html',
    "<div ng-include=\"'components/navbar/navbar.html'\"></div><div class=\"panel panel-xs\"><alert ng-repeat=\"alert in alerts\" type={{alert.type}} close=closeAlert($index)>{{alert.msg}}</alert></div><div class=container><h2>User Deletion</h2><ul class=list-group><li class=list-group-item ng-repeat=\"user in users\"><strong>{{user.name}}</strong><br><span class=text-muted>{{user.login}}</span> <a ng-click=deleteUser(user) class=trash><span class=\"glyphicon glyphicon-trash pull-right\"></span></a></li></ul></div><div class=container><h2>Add Event</h2><form class=form name=form ng-submit=addEvent(form) novalidate><div class=form-group ng-class=\"{ 'has-success': form.name.$valid && submitted,\n" +
    "                                            'has-error': form.name.$invalid && submitted }\"><label>Description</label><input name=name class=form-control ng-model=newevent.name required><p class=help-block ng-show=\"form.name.$error.required && submitted\">A description is required</p></div><div class=form-inline ng-class=\"{ 'has-success': form.attrs.$valid && submitted,\n" +
    "                                            'has-error': form.attrs.$invalid && submitted }\"><label>Attributes</label><br><input onlydigits size=9 ng-model=newevent.attrs.str class=form-control placeholder=Strength> <input onlydigits size=9 ng-model=newevent.attrs.dex class=form-control placeholder=Dexterity> <input onlydigits size=9 ng-model=newevent.attrs.con class=form-control placeholder=Constitution> <input onlydigits size=9 ng-model=newevent.attrs.int class=form-control placeholder=Intelligence> <input onlydigits size=9 ng-model=newevent.attrs.wis class=form-control placeholder=Wisdom> <input onlydigits size=9 ng-model=newevent.attrs.cha class=form-control placeholder=Charisma><p class=help-block ng-show=\"form.attrs.$error.required && submitted\">Doesn't look like a valid email.</p></div><br><div class=form-group ng-class=\"{ 'has-success': form.parent_name.$valid && submitted,\n" +
    "                                            'has-error': form.parent_name.$invalid && submitted }\"><select class=\"form-control dropdown-toggle\" ng-options=\"event.name for event in awesomeEvents | filter:{parent_name:'!'}\" ng-model=newevent.parent_name><option value>-- Select a Category --</option></select><p class=help-block ng-show=\"form.parent_name.$error.required && submitted\">Event must have a category</p></div><br><div><button class=\"btn btn-primary\" type=submit ng-disabled=!form.$valid>Add</button></div></form></div><div class=container><h2>Remove Events</h2><ul class=list-group><li class=list-group-item ng-repeat=\"event in awesomeEvents | filter:{parent_name:'!!'}\"><strong>{{event.name}}</strong><br><ul class=list-inline><li ng-repeat=\"attr in event.attrs\"><span class=text-muted>+{{attr.points}} to {{attr.name}}</span></li></ul><a ng-click=deleteEvent(event) class=trash><span class=\"glyphicon glyphicon-trash pull-right\"></span></a></li></ul></div>"
  );


  $templateCache.put('app/main/main.html',
    "<div ng-include=\"'components/navbar/navbar.html'\"></div><header class=hero-unit id=banner><h1 class=page-header>Attributes</h1><div class=container-fluid><div><ul class=list-unstyled><li><img src=assets/images/str.png alt=Strength width=50 title=Strength> <span style=font-size:30px>{{getAttr('str') || 0}}</span></li><li><img src=assets/images/dex.png alt=Dexterity width=50 title=Dexterity> <span style=font-size:30px>{{getAttr('dex') || 0}}</span></li><li><img src=assets/images/con.png alt=Constitution width=50 title=Constitution> <span style=font-size:30px>{{getAttr('con') || 0}}</span></li><li><img src=assets/images/int.png alt=Intelligence width=50 title=Intelligence> <span style=font-size:30px>{{getAttr('int') || 0}}</span></li><li><img src=assets/images/wis.png alt=Wisdom width=50 title=Wisdom> <span style=font-size:30px>{{getAttr('wis') || 0}}</span></li><li><img src=assets/images/cha.png alt=Charisma width=50 title=Charisma> <span style=font-size:30px>{{getAttr('cha') || 0}}</span></li></ul></div></div></header><div class=container><div class=row><div class=col-lg-12><h1 class=page-header>Log</h1><accordion close-others=true><accordion-group ng-repeat=\"parent in awesomeEvents | filter:{parent_name:'!'}\" heading=\"{{parent.name | titleCase}}\"><div ng-repeat=\"child in awesomeEvents | filter:{parent_name:parent.name}\" class=accordion-inner><a href=\"\" ng-click=updateAttr(child.attrs)>{{child.name | titleCase}}</a></div></accordion-group></accordion></div></div></div><footer class=footer><div class=container><p>Created using Angular Fullstack v2.0.13</p></div></footer>"
  );


  $templateCache.put('app/modal/modal.html',
    "<div class=modal-header><button ng-if=modal.dismissable type=button ng-click=$dismiss() class=close>&times;</button><h4 ng-if=modal.title ng-bind=modal.title class=modal-title></h4></div><div class=modal-body><p ng-if=modal.text ng-bind=modal.text></p><div ng-if=modal.html ng-bind-html=modal.html></div></div><div class=modal-footer><button ng-repeat=\"button in modal.buttons\" ng-class=button.classes ng-click=button.click($event) ng-bind=button.text class=btn></button></div>"
  );


  $templateCache.put('components/navbar/navbar.html',
    "<div class=\"navbar navbar-default navbar-static-top\" ng-controller=NavbarCtrl><div class=container><div class=navbar-header><button class=navbar-toggle type=button ng-click=\"isCollapsed = !isCollapsed\"><span class=sr-only>Toggle navigation</span> <span class=icon-bar></span> <span class=icon-bar></span> <span class=icon-bar></span></button> <a href=\"/\" class=navbar-brand>winatlife</a></div><div collapse=isCollapsed class=\"navbar-collapse collapse\" id=navbar-main><ul class=\"nav navbar-nav\"><li ng-repeat=\"item in menu\" ng-class=\"{active: isActive(item.link)}\"><a ng-href={{item.link}}>{{item.title}}</a></li><li ng-show=isAdmin() ng-class=\"{active: isActive('/admin')}\"><a href=/admin>Admin</a></li></ul><ul class=\"nav navbar-nav navbar-right\"><li ng-hide=isLoggedIn() ng-class=\"{active: isActive('/signup')}\"><a href=/signup>Sign up</a></li><li ng-hide=isLoggedIn() ng-class=\"{active: isActive('/login')}\"><a href=/login>Login</a></li><li ng-show=isLoggedIn()><p class=navbar-text>Hello {{ getCurrentUser().name }}</p></li><li ng-show=isLoggedIn() ng-class=\"{active: isActive('/settings')}\"><a href=/settings><span class=\"glyphicon glyphicon-cog\"></span></a></li><li ng-show=isLoggedIn() ng-class=\"{active: isActive('/logout')}\"><a href=\"\" ng-click=logout()>Logout</a></li></ul></div></div></div>"
  );

}]);
